name: Test Pipeline

on:
  # Triggers the workflow on push or pull request events but for the dev branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tabs
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Listing normally
        run: |
          ls
          
      - name: Using Output command
        run: |
          OUTPUT= echo "::set-output name=OUTPUT::$(ls)"
        id: version
        env:
          OUTPUT: ${{ env.OUTPUT }}
        
      - name: Testing environmental
        run: |
          echo ${{ steps.version.outputs.OUTPUT }}
          
      - name: Testing environmental 2    
          echo ${{ env.OUTPUT }}
      
