name: Test Pipeline

on:
  # Triggers the workflow on push or pull request events but for the dev branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tabs
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Listing normally
        run: |
          ls
          
      - name: Using Output command
        run: |
          OUTPUT= echo "::set-output name=OUTPUT::$(echo "hello")"
        id: version
        env:
          OUTPUT: ${{ env.OUTPUT }}
        
      - name: Testing environmental
        run: |
          echo ${{ steps.version.outputs.OUTPUT }}
          
      - name: Testing environmental 2
        run: |
          echo ${{ env.OUTPUT }}
          
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ gsteps.version.outputs.OUTPUT == 'hello' }}
          if_true: "It works"
          if_false: "Doesn't work"

      - name: Use conditional value
        run: echo "${{ steps.condval.outputs.value }}"
         
        
      
