name: Test Pipeline

on:
  # Triggers the workflow on push or pull request events but for the dev branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tabs
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
      
      - name: Listing normally
        run: |
          ls
          
      - name: Using Output command
        uses: actions/github-script@v3
        id: version
        with:
          script: return "Update"
          result-encoding: string  
#        run: |
#          OUTPUT= echo "::set-output name=OUTPUT::$(echo "Update")"
        
        env:
          OUTPUT: ${{ env.OUTPUT }}
        
      - name: Testing environmental
        run: |
          echo ${{ steps.version.outputs.result }}
          
      - name: Testing environmental 2
        run: |
          echo ${{ env.OUTPUT }}
          
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ steps.version.outputs.result == 'Update Command' }}
          if_true: "Create"
          if_false: "Update"

      - name: Use conditional value
        run: echo "${{ steps.condval.outputs.value }}"

      - name: Testing with create
        if: ${{ steps.version.outputs.result }} == "Create"
        run: |
          echo "Creating the lamda"
          
      - name: Testing with update
        if: ${{ steps.version.outputs.result }} == "Update"
        run: |
          echo "Updating the lamda"
          
      - name: Testing with normal if
        if: ${{ steps.version.outputs.OUTPUT }} == "hello"
        run: |
          echo "nice" 
          ls
        
        
      
