name: Chessboard Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but for the dev branch
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install yarn dependencies and build project
        run: |
          ls
